import sharp from "sharp";
import type { Catalog, CatalogItem } from "./types";

export async function imageFingerprint(buffer: Buffer): Promise<string> {
  const data = await sharp(buffer)
    .rotate()
    .resize(12, 12, { fit: "cover" })
    .grayscale()
    .raw()
    .toBuffer();
  let sum = 0;
  for (const value of data) sum += value;
  const avg = sum / data.length;
  let bits = "";
  for (const value of data) bits += value >= avg ? "1" : "0";
  let hex = "";
  for (let i = 0; i < bits.length; i += 4) {
    hex += Number.parseInt(bits.slice(i, i + 4).padEnd(4, "0"), 2).toString(16);
  }
  return hex;
}

function hamming(a: string, b: string) {
  if (a.length !== b.length) return 99;
  let distance = 0;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) distance += 1;
  }
  return distance;
}

export function isNearDuplicate(hash: string, seen: string[], maxDistance = 6) {
  return seen.some((other) => other && hamming(hash, other) <= maxDistance);
}

export function normalizeTitle(title: string) {
  return title.replace(/^File:/i, "").replace(/\.[a-z0-9]+$/i, "").trim().toLowerCase();
}

export function isJunkTitle(title: string) {
  return /ilce-|dsc\d{4}|starr-\d{6}|dxo_redo|_dscep|zombomeme|\d{4}-\d{2}-\d{2}_\d{2}-\d{2}|^\d{8}_\d{6}$/i.test(
    title.trim(),
  );
}

const UNSAFE_TEXT =
  /\b(penis|vagina|pussy|porn|porno|nsfw|xxx\b|onlyfans|bdsm|fetish|blowjob|hentai|genital|nude selfie|sex tape|cock ring|prince albert)\b/i;
const UNSAFE_AUTHOR = /hookedupky|204235240@n07/i;
const AI_TEXT =
  /midjourney|stable[\s-]?diffusion|dall-?e|dall·e|chatgpt|openai sora|leonardo\.ai|novelai|adobe firefly|ideogram|flux\.1|\bflux ai\b|ai[\s-]?generated|generated by ai|created with ai|made with ai|ai art\b|ai artwork|aigc|人工智能|AI生成|AI绘画|mj prompt|stablediffusion|civitai|tensor\.art|this person does not exist/i;

export function isAiGenerated(text: string) {
  return AI_TEXT.test(text);
}

export function isUnsafeItem(item: {
  title?: string;
  author?: string;
  photographer?: string;
  pageUrl?: string;
  fileKey?: string;
}) {
  const blob = `${item.title ?? ""} ${item.author ?? ""} ${item.photographer ?? ""} ${item.pageUrl ?? ""} ${item.fileKey ?? ""}`;
  return (
    UNSAFE_AUTHOR.test(blob) ||
    UNSAFE_TEXT.test(blob) ||
    isAiGenerated(blob) ||
    isJunkTitle(item.title ?? "")
  );
}

export function isSpecificTitle(title: string) {
  const text = normalizeTitle(title);
  if (text.length < 18) return false;
  if (/untitled|dsc\d|img[_-]|ilce-|screenshot|still \d+|scene \d+|untitled still/i.test(text)) {
    return false;
  }
  return true;
}

export function isRepeatItem(item: CatalogItem, catalog: Catalog) {
  const hashes = [
    ...(catalog.seenContentHashes ?? []),
    ...catalog.items.map((row) => row.contentHash).filter((value): value is string => Boolean(value)),
  ];
  if (item.contentHash && isNearDuplicate(item.contentHash, hashes)) return true;
  if (isSpecificTitle(item.title)) {
    const key = normalizeTitle(item.title);
    return catalog.items.some(
      (row) => row.id !== item.id && normalizeTitle(row.title) === key,
    );
  }
  return false;
}
